### ISSUE TITLE
test-endpoint.sh doesn't use proxy

### ISSUE THREAD

**Issue by DavePickard1234** [DataDog/datadog-cloudfoundry-buildpack#69]
The test-endpoint.sh script contains an nc command in it:
    nc -w5 $LOGS_ENDPOINT $LOGS_PORT < /dev/null

If this is behind a proxy then it will fail so whilst various proxy environment variables are supported the agent won't ever start because this nc command fails.  

To be honest I'm not 100% sure of this but this is what seems to be happening for us and the error message produced within that file is the one we're seeing both in logs and in Datadog alerts (which do use the proxy).

**Comment by nmuesch** [comment]
Hey, @DavePickard1234  thanks for the issue report, apologies for any inconvenience here. The `nc` command currently uses a variable URL that is determined based on some specific config options set in the app manifest. (More context in the comment here - https://github.com/DataDog/datadog-cloudfoundry-buildpack/blob/master/lib/test-endpoint.sh#L40-L44)

I was able to get the test validation to look at an example proxy by specifying the following fields in a test app:

```
    env:
      DD_API_KEY: <API_KEY>
      DD_LOGS_CONFIG_USE_HTTP: true
      DD_PROXY_HTTPS: "<proxy_url>"
      DD_LOGS_ENABLED: "true"
      LOGS_CONFIG: '<logs_config>'
```

(and the `DD_USE_EU: true` if using an eu org)

If you continue to hit any issues, could you provide your app manifest (removing anything sensitive) and any errors you're seeing?
